#!/usr/bin/env python3
"""
Generates every rendering of the FocusMark from one set of numbers.

The mark comes from the Claude Design project "Focus app icon design",
variant b2 ("Broken Arc — refined"). There it is a conic-gradient disc with a
radial-gradient mask punching out the centre, which is not something a
VectorDrawable can express, so it is re-cut here as a single stroked arc.

That conversion was verified rather than eyeballed: the CSS definition was
rasterised from its own maths and diffed against a render of this arc, giving
a mean difference of 0.125/255 with disagreement only on antialiased edges.
The constants below are the em-fractions that came out of it.

CSS conic angles run clockwise from north; SVG and PIL both run clockwise from
east, hence the -90 in ARC_START.

    python3 tools/brand_assets.py
"""

import math
import os

from PIL import Image, ImageDraw, ImageFont

# ── the mark, in fractions of its own em box ──────────────────────────────
OUTER_R = 0.43000        # ring outer radius
STROKE = 0.22897         # ring thickness
CENTER_R = 0.31551       # centreline the stroke is hung on
DOT_R = 0.075            # centre dot radius
ARC_START = 118.0        # 208deg conic, less 90
ARC_SWEEP = 259.2        # 0.72turn of colour; the remaining 100.8deg is the gap

# ── how big the mark sits in each frame ───────────────────────────────────
# Android's adaptive canvas is 108dp of which only the middle 72dp survives
# masking, so the mark is held to 56% and clears the 66dp safe circle. A flat
# export has no mask to fear and uses the 2/3 the design sheet shows.
ADAPTIVE_FRACTION = 0.56
FLAT_FRACTION = 2 / 3

INK = (16, 16, 16)       # #101010, the design's field
BONE = (245, 244, 241)   # #F5F4F1, the design's mark
FONT_LIGHT = "/usr/share/fonts/google-noto/NotoSans-Light.ttf"


def arc_endpoints(cx, cy, r):
    """Start and end of the arc centreline, in drawing coordinates."""
    a0, a1 = math.radians(ARC_START), math.radians(ARC_START + ARC_SWEEP)
    return ((cx + r * math.cos(a0), cy + r * math.sin(a0)),
            (cx + r * math.cos(a1), cy + r * math.sin(a1)))


def vector_drawable(path, canvas=108, fraction=ADAPTIVE_FRACTION, color="#F5F4F1"):
    """Android VectorDrawable: one stroked arc plus the dot."""
    em = canvas * fraction
    c = canvas / 2.0
    r, w, dot = CENTER_R * em, STROKE * em, DOT_R * em
    (x0, y0), (x1, y1) = arc_endpoints(c, c, r)
    large = 1 if ARC_SWEEP > 180 else 0

    xml = f'''<?xml version="1.0" encoding="utf-8"?>
<!--
    The FocusMark: a session ring with a deliberate gap, and a fixed centre dot.
    The loop does not close on its own.

    Generated by tools/brand_assets.py — edit the constants there, not this
    file. In the source design this is a conic gradient behind a radial mask;
    it is re-cut here as a stroked arc, which renders identically and is the
    only form a VectorDrawable can hold.

    The mark occupies {fraction:.0%} of the {canvas}dp canvas, so its {2 * OUTER_R * em:.1f}dp
    width clears the 66dp safe circle no matter which mask a launcher applies.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{canvas}dp"
    android:height="{canvas}dp"
    android:viewportWidth="{canvas}"
    android:viewportHeight="{canvas}">

    <!-- Ring: {ARC_SWEEP:g}deg of arc from {ARC_START:g}deg, leaving a {360 - ARC_SWEEP:.1f}deg gap. -->
    <path
        android:strokeColor="{color}"
        android:strokeWidth="{w:.4f}"
        android:strokeLineCap="butt"
        android:pathData="M{x0:.4f},{y0:.4f} A{r:.4f},{r:.4f} 0 {large} 1 {x1:.4f},{y1:.4f}" />

    <!-- Centre dot. -->
    <path
        android:fillColor="{color}"
        android:pathData="M{c},{c - dot:.4f} A{dot:.4f},{dot:.4f} 0 1 0 {c},{c + dot:.4f} A{dot:.4f},{dot:.4f} 0 1 0 {c},{c - dot:.4f} Z" />
</vector>
'''
    open(path, "w").write(xml)
    print(f"{path}  {canvas}dp  mark {2 * OUTER_R * em:.1f}dp")


def draw_mark(d, cx, cy, em, color):
    """PIL rendering of the same geometry. PIL grows arc width inward from the
    bounding box, so the box is the outer circle and width is the stroke."""
    outer, w, dot = OUTER_R * em, STROKE * em, DOT_R * em
    d.arc([cx - outer, cy - outer, cx + outer, cy + outer],
          ARC_START, ARC_START + ARC_SWEEP, fill=color, width=round(w))
    d.ellipse([cx - dot, cy - dot, cx + dot, cy + dot], fill=color)


def icon(path, size=512, ss=4):
    img = Image.new("RGB", (size * ss,) * 2, INK)
    draw_mark(ImageDraw.Draw(img), size * ss / 2, size * ss / 2,
              size * ss * FLAT_FRACTION, BONE)
    img.resize((size, size), Image.LANCZOS).save(path, "PNG")
    print(f"{path}  {size}x{size}")


def banner(path, w=1024, h=500, ss=2):
    img = Image.new("RGB", (w * ss, h * ss), INK)
    layer = Image.new("RGBA", img.size, (0, 0, 0, 0))
    d = ImageDraw.Draw(layer)

    title_text, sub_text = "focusphone", "the apps you blocked stay blocked"
    title = ImageFont.truetype(FONT_LIGHT, 84 * ss)
    sub = ImageFont.truetype(FONT_LIGHT, 32 * ss)

    # Mark and text are measured and centred as one lockup, so the image
    # survives being cropped on either side.
    em = 210 * ss
    mark_r, gap = OUTER_R * em, 74 * ss
    text_w = max(d.textlength(title_text, font=title), d.textlength(sub_text, font=sub))
    left = (w * ss - (mark_r * 2 + gap + text_w)) / 2

    draw_mark(d, left + mark_r, h * ss / 2, em, BONE + (255,))
    x = left + mark_r * 2 + gap
    d.text((x, 232 * ss), title_text, font=title, fill=BONE + (255,), anchor="ls")
    d.text((x, 292 * ss), sub_text, font=sub, fill=BONE + (115,), anchor="ls")

    Image.alpha_composite(img.convert("RGBA"), layer).convert("RGB") \
        .resize((w, h), Image.LANCZOS).save(path, "PNG")
    print(f"{path}  {w}x{h}  margin {left / ss:.0f}px each side")


if __name__ == "__main__":
    os.makedirs("brand", exist_ok=True)
    vector_drawable("app/src/main/res/drawable/ic_launcher_foreground.xml")
    icon("brand/icon-512.png")
    banner("brand/banner.png")
